# Location of files and folders

# Model weights
model_path: "models/yolo112025-04-23default_e200_p20_b-1_augment/weights/best.pt"

# Images folder
images_folder: "/home/vcv/vespcv/data/images"

# Log file location
log_file_path: 'data/logs/detector.log'


# Detection settings

# Confidence threshold for detection
# A higher threshold means the model is more confident about the detection
# Default is 0.80
conf_threshold: 0.80

# Class names for detection
class_names: ['amel', 'vcra', 'vespsp', 'vvel', 'vzon']


# Camera settings

# Lens position settings
# 10: Close-up approximately 10 cm
# 1: Medium distance, approximately 1 meter
# 0: Far distance, approximately 3 meters
# Test lens position with:
# libcamera-still -t 0 --autofocus-mode continuous --info-text "%lp"
lensposition: 1

# Autofocus settings
autofocus: true  # Enable or disable autofocus
autofocus_mode: "continuous"  # Options: "continuous", "single", etc.


# Capture settings
# Interval in seconds between captures
capture_interval: 15

# Chart interval in minutes for grouping detections
chart_interval: 15


# GPIO settings

# LED Configuration
led:
  pin: 21  # GPIO pin number for the LED
  on_duration: 3  # Duration in seconds that the LED stays on after detection
