# Location of the model weights
model_path: "/home/vcv/vespcv/models/yolo112025-04-23_e200_p20_b-1_L4/weights/best.pt"

# Locaton of the images folder
images_folder: "/home/vcv/vespcv/data/images"

# Confidence threshold for detection
# A higher threshold means the model is more confident about the detection
conf_threshold: 0.80

# lens position 10: Close-up approximately10 c
# lens position  1: Medium distance, approximately 1 meter
# lens position  0: Far distance, approximately 3 meters
# test lenspostition with:
# libcamera-still -t 0 --autofocus-mode continuous --info-text "%lp"
lensposition: 1

# Interval in seconds between captures
capture_interval: 15
