# VespaCV Configuration File
# ========================

# File System Configuration
# ------------------------
model_path: "models/yolo112025-04-23default_e200_p20_b-1_augment/weights/best.pt"
images_folder: "/home/vcv/vespcv/data/images"
log_file_path: 'data/logs/detector.log'

# Detection Configuration
# ----------------------
# Confidence threshold (0.0 - 1.0)
# Higher values require stronger confidence for detections
conf_threshold: 0.80

# Target species for detection
class_names: ['amel', 'vcra', 'vespsp', 'vvel', 'vzon']


# Timing Configuration
# ------------------
# Time between consecutive image captures (in seconds)
capture_interval: 15

# Time window for grouping detections in charts (in minutes)
chart_interval: 15

# Hardware Configuration
# --------------------
# GPIO control settings
led:
  pin: 21          # GPIO pin number for the LED
  on_duration: 3   # LED activation duration after detection (in seconds)
