# Location of the model weights
model_path: "models/yolo112025-04-23default_e200_p20_b-1_augment/weights/best.pt"

# Locaton of the images folder
images_folder: "/home/vcv/vespcv/data/images"

# Location of the logfile
log_file_path: 'data/logs/detector.log'

# Confidence threshold for detection
# A higher threshold means the model is more confident about the detection
conf_threshold: 0.70

# Class names
class_names: ['amel', 'vcra', 'vespsp', 'vvel', 'vzon']

# lens position 10: Close-up approximately10 c
# lens position  1: Medium distance, approximately 1 meter
# lens position  0: Far distance, approximately 3 meters
# test lenspostition with:
# libcamera-still -t 0 --autofocus-mode continuous --info-text "%lp"
lensposition: 1

# Interval in seconds between captures
capture_interval: 15

# Chart interval in minutes for grouping detections
chart_interval: 15

# LED Configuration
led:
  pin: 21  # GPIO pin number for the LED
  on_duration: 3  # Duration in seconds that the LED stays on after detection
